// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfJPHRy-GvF_0f7SIeiHWxs9lSAVKyFT0',
    appId: '1:449874418886:web:b7bcad8398adfa49a5cbc7',
    messagingSenderId: '449874418886',
    projectId: 'snacc-app-jyo',
    authDomain: 'snacc-app-jyo.firebaseapp.com',
    storageBucket: 'snacc-app-jyo.appspot.com',
    measurementId: 'G-PJKG5N1XJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBWqntgklbbmqjt02R2OClu4oGwfjdkck',
    appId: '1:449874418886:android:4d36de770e264648a5cbc7',
    messagingSenderId: '449874418886',
    projectId: 'snacc-app-jyo',
    storageBucket: 'snacc-app-jyo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcv8EHlA-8ceOoJqX08bzK6XJE7WlHEnY',
    appId: '1:449874418886:ios:4c2802300bf7202aa5cbc7',
    messagingSenderId: '449874418886',
    projectId: 'snacc-app-jyo',
    storageBucket: 'snacc-app-jyo.appspot.com',
    iosBundleId: 'com.example.snacc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcv8EHlA-8ceOoJqX08bzK6XJE7WlHEnY',
    appId: '1:449874418886:ios:54d644e25fbac9bba5cbc7',
    messagingSenderId: '449874418886',
    projectId: 'snacc-app-jyo',
    storageBucket: 'snacc-app-jyo.appspot.com',
    iosBundleId: 'com.example.snacc.RunnerTests',
  );
}
